// <auto-generated />
namespace Sistrategia.SAT.CFDiWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SATSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SATSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201511261926247_SATSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
