namespace Sistrategia.SAT.CFDiWebSite.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Banco2016 : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.sat_banco", "razon_social", c => c.String(maxLength: 256));
                        
            Sql("SET IDENTITY_INSERT [dbo].[sat_banco] ON");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (1, '82E2C8AC-06AE-4F61-AFA6-364C731EF65D', '002', 'BANAMEX', 'Banco Nacional de México, S.A., Institución de Banca Múltiple, Grupo Financiero Banamex', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (2, '777AA59F-B61D-47C8-999F-C594670902DE', '006', 'BANCOMEXT', 'Banco Nacional de Comercio Exterior, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (3, 'D84BF5E6-6148-4E0A-89BB-FA327A62A69E', '009', 'BANOBRAS', 'Banco Nacional de Obras y Servicios Públicos, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (4, '7FCD5DC2-9E1C-4A61-AC10-C208769A279E', '012', 'BBVA BANCOMER', 'BBVA Bancomer, S.A., Institución de Banca Múltiple, Grupo Financiero BBVA Bancomer', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (5, '66CF1100-B193-4E4B-AE31-C8CD31CABA25', '014', 'SANTANDER', 'Banco Santander (México), S.A., Institución de Banca Múltiple, Grupo Financiero Santander', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (6, 'EFFD83D2-CDE4-4338-A499-83E2B1A53D23', '019', 'BANJERCITO', 'Banco Nacional del Ejército, Fuerza Aérea y Armada, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (7, '916539D9-9D4C-4D08-8E37-CE524FA9C416', '021', 'HSBC', 'HSBC México, S.A., institución De Banca Múltiple, Grupo Financiero HSBC', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (8, '5A3DAA81-85A5-4CB8-AC8F-B1EB8D2CCF36', '030', 'BAJIO', 'Banco del Bajío, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (9, '9BD78967-FCEB-4F4A-8167-B29077131D53', '032', 'IXE', 'IXE Banco, S.A., Institución de Banca Múltiple, IXE Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (10, '4BE20E91-DD47-4E5C-8B7C-DF211D87A0D7', '036', 'INBURSA', 'Banco Inbursa, S.A., Institución de Banca Múltiple, Grupo Financiero Inbursa', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (11, '56A84082-D7FD-40E7-BB12-677AA35DF291', '037', 'INTERACCIONES', 'Banco Interacciones, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (12, '8A819B15-39EE-493F-9929-CDA816508379', '042', 'MIFEL', 'Banca Mifel, S.A., Institución de Banca Múltiple, Grupo Financiero Mifel', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (13, 'A05074DD-187E-4B2C-97F6-1FA19412FD56', '044', 'SCOTIABANK',	'Scotiabank Inverlat, S.A.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (14, '1B7D2A51-CABD-49F9-8EE7-3610B2D6DEBB', '058', 'BANREGIO', 'Banco Regional de Monterrey, S.A., Institución de Banca Múltiple, Banregio Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (15, 'B5448207-27B2-4128-8A71-644274E65FB4', '059', 'INVEX', 'Banco Invex, S.A., Institución de Banca Múltiple, Invex Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (16, '3BD756B0-6D51-4E87-A598-EE715D20F1D7', '060', 'BANSI', 'Bansi, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (17, 'BA952651-193B-4C92-9BCF-99AC7E23D53E', '062', 'AFIRME', 'Banca Afirme, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (18, '593FD957-CC24-4F77-B45A-85B69917C050', '072', 'BANORTE', 'Banco Mercantil del Norte, S.A., Institución de Banca Múltiple, Grupo Financiero Banorte', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (19, 'CFA3D249-A9C2-4CF0-9431-53FEC69F0187', '102', 'THE ROYAL BANK', 'The Royal Bank of Scotland México, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (20, '709FEFD6-2079-47F8-8505-A8AC944B22D3', '103', 'AMERICAN EXPRESS', 'American Express Bank (México), S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (21, '0263CB2A-99F1-45EF-B37B-022DC00234E1', '106', 'BAMSA', 'Bank of America México, S.A., Institución de Banca Múltiple, Grupo Financiero Bank of America', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (22, '70CD6CBD-9D5E-417C-9516-C5E93579787D', '108', 'TOKYO', 'Bank of Tokyo-Mitsubishi UFJ (México), S.A.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (23, 'AD856F5F-16C2-4E33-A496-4583F5100CB0', '110', 'JP MORGAN', 'Banco J.P. Morgan, S.A., Institución de Banca Múltiple, J.P. Morgan Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (24, 'AD1A80E2-F5EC-46D6-86B6-502EDC1911C2', '112', 'BMONEX', 'Banco Monex, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (25, 'DD3D74F2-B374-40B5-9B18-B8BFA8CCF22B', '113', 'VE POR MAS', 'Banco Ve Por Mas, S.A. Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (26, '3BE9D1B9-8CBD-4BC1-BDBC-0D0F5AD49B04', '116', 'ING', 'ING Bank (México), S.A., Institución de Banca Múltiple, ING Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (27, '79C2531E-F352-4660-B65F-83ACAB978EDA', '124', 'DEUTSCHE', 'Deutsche Bank México, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (28, '07D0BD4E-9F82-493D-A98B-6D60DE5F96D8', '126', 'CREDIT SUISSE', 'Banco Credit Suisse (México), S.A. Institución de Banca Múltiple, Grupo Financiero Credit Suisse (México)', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (29, 'D8428F8F-1E88-4C81-9123-41866D70805D', '127', 'AZTECA','Banco Azteca, S.A. Institución de Banca Múltiple.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (30, '32C67570-6BE3-42C0-ADE3-B60F27614F97', '128', 'AUTOFIN', 'Banco Autofin México, S.A. Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (31, '418F8D16-396C-4921-AB6D-886DD1C1126C', '129', 'BARCLAYS', 'Barclays Bank México, S.A., Institución de Banca Múltiple, Grupo Financiero Barclays México', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (32, 'C66E950F-CA91-4C67-A062-3B2D322AFC56', '130', 'COMPARTAMOS', 'Banco Compartamos, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (33, '5539F7C0-2305-48F2-8F4C-7F7AD5BCF5CA', '131', 'BANCO FAMSA', 'Banco Ahorro Famsa, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (34, '7EE36ED1-869F-4438-8B55-D26EB3FCC926', '132', 'BMULTIVA', 'Banco Multiva, S.A., Institución de Banca Múltiple, Multivalores Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (35, 'AB9634B0-2395-4CBE-A87C-EE8EB568AA13', '133', 'ACTINVER', 'Banco Actinver, S.A. Institución de Banca Múltiple, Grupo Financiero Actinver', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (36, 'EA3697D7-1CE1-4808-AEB8-361829DE3B99', '134', 'WAL-MART', 'Banco Wal-Mart de México Adelante, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (37, '865B2CCF-3262-454F-A905-746E7720ECB1', '135', 'NAFIN', 'Nacional Financiera, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (38, '4D500E0E-305C-446F-8AA1-EA5B4D5C2824', '136', 'INTERBANCO', 'Inter Banco, S.A. Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (39, 'FE797051-AB87-4DBF-BD27-4835DDDEF8BA', '137', 'BANCOPPEL', 'BanCoppel, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (40, '1B5FA516-3090-4B86-8DFE-83614C89B346', '138', 'ABC CAPITAL', 'ABC Capital, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (41, '1BAFCD5E-52AD-449B-9B83-B1126DF793D9', '139', 'UBS BANK', 'UBS Bank México, S.A., Institución de Banca Múltiple, UBS Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (42, '58EE767C-ADD2-4F13-8590-4D7F1DD7FC97', '140', 'CONSUBANCO', 'Consubanco, S.A. Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (43, 'A3C74AA9-6466-4E2A-A5A7-8B9F1DFFE6FF', '141', 'VOLKSWAGEN', 'Volkswagen Bank, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (44, '3AA97E27-8675-47BE-90A5-F737F1C0C576', '143', 'CIBANCO', 'CIBanco, S.A.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (45, 'ABEC21FC-9A76-4B32-A9A0-D7F4D73AAC00', '145', 'BBASE', 'Banco Base, S.A., Institución de Banca Múltiple', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (46, '821434B0-C3BB-4E24-992B-AE4876E9B565', '166', 'BANSEFI', 'Banco del Ahorro Nacional y Servicios Financieros, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (47, 'ACD1CBD7-BB0B-4172-99C7-D59D8FBF3666', '168', 'HIPOTECARIA FEDERAL', 'Sociedad Hipotecaria Federal, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (48, '173975E5-DE90-4A79-ABDC-43AF2375AD91', '600', 'MONEXCB', 'Monex Casa de Bolsa, S.A. de C.V. Monex Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (49, 'B931477E-A6BA-47A1-9162-8156D93F8A0C', '601', 'GBM', 'GBM Grupo Bursátil Mexicano, S.A. de C.V. Casa de Bolsa', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (50, '927AE41B-810B-442F-8C5A-F12F52993357', '602', 'MASARI', 'Masari Casa de Bolsa, S.A.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (51, '27ED07DE-20CB-4B31-86AB-DAF1E7F2B2D0', '605', 'VALUE', 'Value, S.A. de C.V. Casa de Bolsa', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (52, 'BA5C741F-632A-4E36-89FD-75386511C349', '606', 'ESTRUCTURADORES', 'Estructuradores del Mercado de Valores Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (53, '99A36EFD-B19F-4661-B0D8-88EE73E85892', '607', 'TIBER', 'Casa de Cambio Tiber, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (54, '60481CEE-9E14-4781-BDF6-9498C227EB19', '608', 'VECTOR', 'Vector Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (55, 'D1AE84B9-D0FA-4440-8AFC-A74730FA48EB', '610', 'B&B', 'B y B, Casa de Cambio, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (56, '8195BFCC-DFDB-43FD-8C60-0FE5E89EC0F9', '614', 'ACCIVAL', 'Acciones y Valores Banamex, S.A. de C.V., Casa de Bolsa', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (57, '7067CE66-3D3F-49C0-96E0-3C74CA9E903F', '615', 'MERRILL LYNCH', 'Merrill Lynch México, S.A. de C.V. Casa de Bolsa', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (58, 'EAC1C795-B45C-4BA0-AEEB-B34598DA2BBD', '616', 'FINAMEX', 'Casa de Bolsa Finamex, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (59, '3FC3DB0B-70F9-4DBB-8395-C36C1FF7B4BC', '617', 'VALMEX', 'Valores Mexicanos Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (60, 'BCD97A89-F572-4BF2-9BB3-CA6A28322D61', '618', 'UNICA', 'Unica Casa de Cambio, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (61, '09C9BDF8-D8C6-43AF-B16E-817D694EF777', '619', 'MAPFRE', 'MAPFRE Tepeyac, S.A.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (62, 'BF15F6F0-70AD-4FF8-98ED-F5B1BFD8FDE4', '620', 'PROFUTURO', 'Profuturo G.N.P., S.A. de C.V., Afore', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (63, '8880D21F-8B25-4EDD-92EF-01CF0CAC923E', '621', 'CB ACTINVER', 'Actinver Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (64, '481D3716-D671-4B2F-A7B0-2EE372651FD9', '622', 'OACTIN', 'OPERADORA ACTINVER, S.A. DE C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (65, '2D63783B-FFF3-4E5E-A262-E62354EB14F9', '623', 'SKANDIA', 'Skandia Vida, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (66, 'CFD42B00-1220-4565-B950-7ADFF1A7ADB1', '626', 'CBDEUTSCHE', 'Deutsche Securities, S.A. de C.V. CASA DE BOLSA', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (67, '2AFA8331-801B-446B-8EEB-6B3BB07B464E', '627', 'ZURICH', 'Zurich Compañía de Seguros, S.A.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (68, 'AD70330D-E90D-4689-916F-F30605E65F87', '628', 'ZURICHVI', 'Zurich Vida, Compañía de Seguros, S.A.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (69, '540A401A-41EA-4722-B0DF-A29283679E06', '629', 'SU CASITA', 'Hipotecaria Su Casita, S.A. de C.V. SOFOM ENR', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (70, '8C19CFE2-06DF-474E-9627-8CCA826A8D56', '630', 'CB INTERCAM', 'Intercam Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (71, '69AE9F5B-A3CD-4745-8C75-DF48FF335563', '631', 'CI BOLSA', 'CI Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (72, '24115FD7-A186-4C87-809B-F88425BB34F0', '632', 'BULLTICK CB', 'Bulltick Casa de Bolsa, S.A., de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (73, '01280804-F327-4B8C-9C6F-0D39520D8D40', '633', 'STERLING', 'Sterling Casa de Cambio, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (74, '807A03E4-B2E6-4598-B70F-55B25E9A669A', '634', 'FINCOMUN', 'Fincomún, Servicios Financieros Comunitarios, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (75, '50C162FD-1E09-437B-8584-AAB068C4A908', '636', 'HDI SEGUROS', 'HDI Seguros, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (76, '3402BA11-C2D8-4C80-8543-DC94CDB25590', '637', 'ORDER', 'Order Express Casa de Cambio, S.A. de C.V', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (77, '3F3CF46D-F5E7-4A1E-9691-57A6760B8AB8', '638', 'AKALA', 'Akala, S.A. de C.V., Sociedad Financiera Popular', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (78, '6FFCA687-79EC-4F93-A32B-5BC242B24B5C', '640', 'CB JPMORGAN', 'J.P. Morgan Casa de Bolsa, S.A. de C.V. J.P. Morgan Grupo Financiero', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (79, '8A64FE1F-BC9D-41FF-B4B3-86C38CC847E2', '642', 'REFORMA', 'Operadora de Recursos Reforma, S.A. de C.V., S.F.P.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (80, 'ACACD287-8087-4DE3-9449-69208681C939', '646', 'STP', 'Sistema de Transferencias y Pagos STP, S.A. de C.V.SOFOM ENR', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (81, '73E59E6A-2145-4D90-A25F-295F2CE46664', '647', 'TELECOMM', 'Telecomunicaciones de México', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (82, '0B725D13-F65E-4351-9CA6-D82907D6ADD5', '648', 'EVERCORE', 'Evercore Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (83, '17A73CCE-0AF0-4C6B-9409-72933482CC74', '649', 'SKANDIA', 'Skandia Operadora de Fondos, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (84, '54E79919-9138-43A4-9112-08A6C86EADAC', '651', 'SEGMTY', 'Seguros Monterrey New York Life, S.A de C.V', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (85, '237167CC-1A8C-47E1-84D9-CA7D46FF33E7', '652', 'ASEA', 'Solución Asea, S.A. de C.V., Sociedad Financiera Popular', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (86, 'F88061A0-AC64-46AD-810F-DF348278A84F', '653', 'KUSPIT', 'Kuspit Casa de Bolsa, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (87, '323BE153-A867-442E-9726-3806D7F92DEA', '655', 'SOFIEXPRESS', 'J.P. SOFIEXPRESS, S.A. de C.V., S.F.P.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (88, 'B49CCDB3-5C71-470D-B06F-3A4B7B987C96', '656', 'UNAGRA', 'UNAGRA, S.A. de C.V., S.F.P.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (89, '6BE2C9C2-4B46-4F83-892C-BAC8B9C7C06D', '659', 'OPCIONES EMPRESARIALES DEL NOROESTE', 'OPCIONES EMPRESARIALES DEL NORESTE, S.A. DE C.V., S.F.P.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (90, '48FC4A97-333F-4F35-A93A-8A06859F6966', '901', 'CLS', 'Cls Bank International', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (91, '45B3D7F0-3FC5-46F7-BB98-ACADC90C0485', '902', 'INDEVAL', 'SD. Indeval, S.A. de C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (92, 'C47A128F-F435-4E36-A314-FDDB55724E5D', '670', 'LIBERTAD', 'Libertad Servicios Financieros, S.A. De C.V.', 'A')");
            Sql("INSERT INTO [dbo].[sat_banco] ([banco_id], [public_key], [clave], [nombre_corto], [razon_social],[status]) VALUES (93, '48B14A2B-6E9C-4D4C-8BDE-EA784E5F92FD', '999', 'N/A', NULL, 'A')");
            Sql("SET IDENTITY_INSERT [dbo].[sat_banco] OFF");
        }
        
        public override void Down()
        {
            Sql("DELETE FROM [dbo].[sat_banco]");
            AlterColumn("dbo.sat_banco", "razon_social", c => c.String(nullable: false, maxLength: 256));
        }
    }
}
